<a href="https://colab.research.google.com/github/Saswati-Dash/Python-/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
'''
Diffrence between Python list & numpy Array
Python list :-
speed - slow
memory - user more
calculation - need loops
best for small data


Numpy Array :-
speed - 50 to 100 times faster
memory - use less
best for large data set

'''

'\nDiffrence between Python list & numpy Array\nPython list :-\nspeed - slow\nmemory - user more\ncalculation - need loops\nbest for small data\n\n\nNumpy Array :-\nspeed - 50 to 100 times faster\nmemory - use less\nbest for large data set\n\n'

In [95]:
import numpy as np

In [96]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [97]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
# 3-dimensional array - matrix

In [99]:
np.matrix

numpy.matrix

In [100]:
type(arr_2d)

numpy.ndarray

In [101]:
arr_2d.ndim

2

In [102]:
# creating array from list

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [103]:
type(arr)

numpy.ndarray

In [104]:
# with default values
# shape - for size
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [105]:
# with default values as 1
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [106]:
# full function - full(shape , value)
# if i want to set default value any number for example 7
filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [107]:
# creating sequence of number in numpy
# arange function it is same as range function only diffrence is it return a numpy array
# syntax - arange(start,stop,step)

arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [108]:
# creating identity matrices . identity matrix - 1 in diagonal and 0 else their
# syntax - eye(size)
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy_Array_Property



In [109]:
# Numpy properties

How to check shape , size , type of array

In [110]:
# Shape - working with multi dimensiional data - result rows and columns


In [111]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
print(arr_2d.shape)

(3, 3)


In [113]:
# Size - total number of element in a array

In [114]:
print(arr_2d.size)

9


In [115]:
# ndim - number of dimenstion

In [116]:
print(arr_2d.ndim)

2


In [117]:
# dtype - data type of element

In [118]:
print(arr_2d.dtype)

int64


In [119]:
# changing datatype - astype() - to change it datatype to other datatype
# for ex - number to text , int to float
#arr.array(newtype) newtype can be - int , float , string

In [120]:
arr_1 = np.array([1.2,2.5,3.8])

In [121]:
int_ary = arr_1.astype(int)

In [122]:
print(int_ary)

[1 2 3]


In [123]:
print(int_ary.dtype)

int64


In [124]:
# Numpy Mathematical Operation

In [125]:
'''
Operator
+ - arr+2
- - arr-2
* - arr*2
/ - arr/2
** - arr**2
// - arr//2
% - arr % 2

'''

'\nOperator\n+ - arr+2\n- - arr-2\n* - arr*2\n/ - arr/2\n** - arr**2\n// - arr//2\n% - arr % 2\n\n'

In [126]:
arrO = np.array([10,20,30])

In [127]:
print(arrO + 5)
print(arrO - 5)
print(arrO * 5)
print(arrO / 5)
print(arrO ** 5)
print(arrO // 5)
print(arrO % 5)


[15 25 35]
[ 5 15 25]
[ 50 100 150]
[2. 4. 6.]
[  100000  3200000 24300000]
[2 4 6]
[0 0 0]


In [128]:
# Aggregation Function
'''
np.sum(array) - add
np.mean(array)- average
np.min(array) - small
np.max(array) - large
np.std(array) - standard deviation -
np.variant(array) - variant -

'''

'\nnp.sum(array) - add\nnp.mean(array)- average\nnp.min(array) - small\nnp.max(array) - large\nnp.std(array) - standard deviation -\nnp.variant(array) - variant -\n\n'

In [129]:
arr_agg = np.array([10,20,30,40,50])

In [130]:
print(np.sum(arr_agg))
print(np.mean(arr_agg))
print(np.min(arr_agg))
print(np.max(arr_agg))
print(np.var(arr_agg))
print(np.std(arr_agg))


150
30.0
10
50
200.0
14.142135623730951


In [131]:
'''
Variance measures:

👉 How much the data is spread out from the mean
Variance=    1​
          __________ ∑(xi​−μ)2
             N
arr = np.array([2,4,6,8])

Step 1: Find Mean
Mean=(2+4+6+8)/4=5

Step 2: Subtract Mean
2 - 5 = -3
4 - 5 = -1
6 - 5 = 1
8 - 5 = 3

Step 3: Square Them
9, 1, 1, 9

Step 4: Take Average
(9+1+1+9)/4=5

answer - 5.0


Standard deviation is:

👉 Square root of variance
StandardDeviation=√Variance
'''

'\nVariance measures:\n\n👉 How much the data is spread out from the mean\nVariance=    1\u200b\n          __________ ∑(xi\u200b−μ)2\n             N\narr = np.array([2,4,6,8])\n\nStep 1: Find Mean\nMean=(2+4+6+8)/4=5\n\nStep 2: Subtract Mean\n2 - 5 = -3\n4 - 5 = -1\n6 - 5 = 1\n8 - 5 = 3\n\nStep 3: Square Them\n9, 1, 1, 9\n\nStep 4: Take Average\n(9+1+1+9)/4=5\n\nanswer - 5.0\n\n\nStandard deviation is:\n\n👉 Square root of variance\nStandardDeviation=√Variance\n'

# Indexing & Slicing

In [132]:
# Indexing & Slicing is used to access the element in array


In [133]:
ind = np.array([1,2,3,4,5])

In [134]:
ind

array([1, 2, 3, 4, 5])

In [135]:
print(ind[0])

1


In [136]:
# Slicing
# array[start,stop,step]
sli = np.array([10,20,30,40,50,60])

In [137]:
print(sli[1:5])
print(sli[:5])
print(sli[::2])
print(sli[::-1])


[20 30 40 50]
[10 20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [138]:
# fancy indexing :- selecting multiple element at once

In [139]:
fan = np.array([10,20,30,40,50,60])

In [140]:
print(fan[[0,2,4]])

[10 30 50]


In [141]:
# Boolean masking - filtering data based on condition


In [142]:
bol = np.array([10,20,30,40,50,60])

In [143]:
print(bol[bol > 25])

[30 40 50 60]


# RESHAPING AND MANIPULATION

In [144]:
'''
Reshaping & Manipulating Array
|
v
changing dimension without modify number of element . no of element will remain same
'''

'\nReshaping & Manipulating Array\n|\nv\nchanging dimension without modify number of element . no of element will remain same\n'

In [145]:
arr3 = np.array([1,2,3,4,5,6])
reshape_arr = arr3.reshape(2,3)
print(reshape_arr)

[[1 2 3]
 [4 5 6]]


In [146]:
# Flattening array
'''
1. ravel - return view - affect original array
2. flatten - return copy - dont affect original array
-- when you want to convert multidimension array into 1d array

'''

'\n1. ravel - return view - affect original array\n2. flatten - return copy - dont affect original array\n-- when you want to convert multidimension array into 1d array\n\n'

In [147]:
arr_4 = np.array([[1,2,3],
                   [4,5,6]])

In [148]:
print(arr_4.flatten())

[1 2 3 4 5 6]


In [149]:
arr_4.ndim

2

In [150]:
# -- only the copy no affected array dimension

In [151]:
rav = arr_4.ravel()

In [152]:
print(rav.ndim)

1


**Advance Numpy**

In [153]:
'''
Insert
Remove
Stack
Split
'''

'\nInsert\nRemove\nStack\nSplit\n'

In [154]:
# Insert
'''
np.insert(array,index,value,axis==none)
axis==none - flaten array
axis- axis = 0 - row wise
      axis = 1 - column wise
'''

'\nnp.insert(array,index,value,axis==none)\naxis==none - flaten array\naxis- axis = 0 - row wise\n      axis = 1 - column wise\n'

In [155]:
arrI = np.array([10,20,30,40,50,60])

In [156]:
new_arr = np.insert(arrI,2,100, axis=0)

In [157]:
print(new_arr)

[ 10  20 100  30  40  50  60]


In [158]:
ar_2d = np.array([[1,2],
                   [3,4]])

In [159]:
new_ar_rd = np.insert(ar_2d,1,[5,6], axis=0)

In [160]:
print(new_ar_rd)

[[1 2]
 [5 6]
 [3 4]]


In [161]:
new_ar_cd = np.insert(ar_2d,1,[5,6], axis=1)

In [162]:
print(new_ar_cd)

[[1 5 2]
 [3 6 4]]


In [163]:
#Append - add element in array at the end

In [164]:
ap_arr = np.array([10,20,30])

In [165]:
new_ap_arr = np.append(ap_arr, [40,50,60])

In [166]:
print(new_ap_arr)

[10 20 30 40 50 60]


In [167]:
# concatenate - join two array
'''
np.concatenate((array1,array2), axis = 0)
axis 0 -- vertical stacking
axis 1 . horizonal stacking

'''

'\nnp.concatenate((array1,array2), axis = 0)\naxis 0 -- vertical stacking\naxis 1 . horizonal stacking\n\n'

In [168]:
con_arr1 = np.array([1,2,3])
con_arr2 = np.array([4,5,6])

In [169]:
new_con_arr = np.concatenate((con_arr1,con_arr2))

In [170]:
new_con_arr

array([1, 2, 3, 4, 5, 6])

In [171]:
# Removing element of array
# np.delete(array, index , axis = none)

In [172]:
re_arr = np.array([10,20,30,40,50,60,70])

In [173]:
new_re_arr = np.delete(re_arr,6)

In [174]:
new_ap_arr

array([10, 20, 30, 40, 50, 60])

In [175]:
re_arr2d = np.array([[1,2,3],
                     [4,5,6]])

In [176]:
new_re_arr2d = np.delete(re_arr2d,0,axis=0)

In [177]:
new_re_arr2d

array([[4, 5, 6]])

In [178]:
new_re_arr2d_1 = np.delete(re_arr2d,2,axis=1)

In [179]:
new_re_arr2d_1

array([[1, 2],
       [4, 5]])

In [180]:
# stack - combining arrays vertically or horizontally
'''
vstack() - row wise
hstack() - column wise

'''

'\nvstack() - row wise\nhstack() - column wise\n\n'

In [182]:
varr1 = np.array([1,2,3])
varr2 = np.array([4,5,6])

In [183]:
print(np.vstack((varr1, varr2)))
print(np.hstack((varr1 , varr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# spliting - to divide array in equal part , horizontal part , vertical part
'''
np.split()
equal
np.hsplit()
np.vsplit()
'''

In [ ]:
sarry = np.array([])