<a href="https://colab.research.google.com/github/Saswati-Dash/Python-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Diffrence between Python list & numpy Array
Python list :-
speed - slow
memory - user more
calculation - need loops
best for small data


Numpy Array :-
speed - 50 to 100 times faster
memory - use less
best for large data set

'''

In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [10]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 3-dimensional array - matrix

In [ ]:
np.matrix

In [5]:
type(arr_2d)

numpy.ndarray

In [6]:
arr_2d.ndim

2

In [9]:
# creating array from list

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [8]:
type(arr)

numpy.ndarray

In [11]:
# with default values
# shape - for size
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [12]:
# with default values as 1
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# full function - full(shape , value)
# if i want to set default value any number for example 7
filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [15]:
# creating sequence of number in numpy
# arange function it is same as range function only diffrence is it return a numpy array
# syntax - arange(start,stop,step)

arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [16]:
# creating identity matrices . identity matrix - 1 in diagonal and 0 else their
# syntax - eye(size)
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy_Array_Property



In [ ]:
# Numpy properties

How to check shape , size , type of array

In [ ]:
# Shape - working with multi dimensiional data - result rows and columns


In [22]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(arr_2d.shape)

(3, 3)


In [ ]:
# Size - total number of element in a array

In [20]:
print(arr_2d.size)

9


In [ ]:
# ndim - number of dimenstion

In [23]:
print(arr_2d.ndim)

2


In [ ]:
# dtype - data type of element

In [24]:
print(arr_2d.dtype)

int64


In [ ]:
# changing datatype - astype() - to change it datatype to other datatype
# for ex - number to text , int to float
#arr.array(newtype) newtype can be - int , float , string

In [25]:
arr_1 = np.array([1.2,2.5,3.8])

In [28]:
int_ary = arr_1.astype(int)

In [29]:
print(int_ary)

[1 2 3]


In [30]:
print(int_ary.dtype)

int64


In [ ]:
# Numpy Mathematical Operation

In [ ]:
'''
Operator
+ - arr+2
- - arr-2
* - arr*2
/ - arr/2
** - arr**2
// - arr//2
% - arr % 2

'''

In [31]:
arrO = np.array([10,20,30])

In [32]:
print(arrO + 5)
print(arrO - 5)
print(arrO * 5)
print(arrO / 5)
print(arrO ** 5)
print(arrO // 5)
print(arrO % 5)


[15 25 35]
[ 5 15 25]
[ 50 100 150]
[2. 4. 6.]
[  100000  3200000 24300000]
[2 4 6]
[0 0 0]


In [ ]:
# Aggregation Function
'''
np.sum(array) - add
np.mean(array)- average
np.min(array) - small
np.max(array) - large
np.std(array) - standard deviation -
np.variant(array) - variant -

'''

In [33]:
arr_agg = np.array([10,20,30,40,50])

In [36]:
print(np.sum(arr_agg))
print(np.mean(arr_agg))
print(np.min(arr_agg))
print(np.max(arr_agg))
print(np.var(arr_agg))
print(np.std(arr_agg))


150
30.0
10
50
200.0
14.142135623730951


In [ ]:
'''
Variance measures:

👉 How much the data is spread out from the mean
Variance=    1​
          __________ ∑(xi​−μ)2
             N
arr = np.array([2,4,6,8])

Step 1: Find Mean
Mean=(2+4+6+8)/4=5

Step 2: Subtract Mean
2 - 5 = -3
4 - 5 = -1
6 - 5 = 1
8 - 5 = 3

Step 3: Square Them
9, 1, 1, 9

Step 4: Take Average
(9+1+1+9)/4=5

answer - 5.0


Standard deviation is:

👉 Square root of variance
StandardDeviation=√Variance
'''

# Indexing & Slicing

In [ ]:
# Indexing & Slicing is used to access the element in array


In [38]:
ind = np.array([1,2,3,4,5])

In [39]:
ind

array([1, 2, 3, 4, 5])

In [40]:
print(ind[0])

1


In [42]:
# Slicing
# array[start,stop,step]
sli = np.array([10,20,30,40,50,60])

In [44]:
print(sli[1:5])
print(sli[:5])
print(sli[::2])
print(sli[::-1])


[20 30 40 50]
[10 20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
# fancy indexing :- selecting multiple element at once

In [45]:
fan = np.array([10,20,30,40,50,60])

In [46]:
print(fan[[0,2,4]])

[10 30 50]


In [ ]:
# Boolean masking - filtering data based on condition


In [47]:
bol = np.array([10,20,30,40,50,60])

In [50]:
print(bol[bol > 25])

[30 40 50 60]


# RESHAPING AND MANIPULATION

In [ ]:
'''
Reshaping & Manipulating Array
|
v
changing dimension without modify number of element . no of element will remain same
'''

In [51]:
arr3 = np.array([1,2,3,4,5,6])
reshape_arr = arr3.reshape(2,3)
print(reshape_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flattening array
'''
1. ravel - return view - affect original array
2. flatten - return copy - dont affect original array
-- when you want to convert multidimension array into 1d array

'''

In [52]:
arr_4 = np.array([[1,2,3],
                   [4,5,6]])

In [53]:
print(arr_4.flatten())

[1 2 3 4 5 6]


In [54]:
arr_4.ndim

2

In [ ]:
# -- only the copy no affected array dimension

In [66]:
rav = arr_4.ravel()

In [67]:
print(rav.ndim)

1


**Advance Numpy**

In [ ]:
'''
Insert
Remove
Stack
Split
'''

In [ ]:
# Insert
'''
np.insert(array,index,value,axis==none)
axis==none - flaten array
axis- axis = 0 - row wise
      axis = 1 - column wise
'''

In [69]:
arrI = np.array([10,20,30,40,50,60])

In [72]:
new_arr = np.insert(arrI,2,100, axis=0)

In [73]:
print(new_arr)

[ 10  20 100  30  40  50  60]


In [74]:
ar_2d = np.array([[1,2],
                   [3,4]])

In [80]:
new_ar_rd = np.insert(ar_2d,1,[5,6], axis=0)

In [81]:
print(new_ar_rd)

[[1 2]
 [5 6]
 [3 4]]


In [82]:
new_ar_cd = np.insert(ar_2d,1,[5,6], axis=1)

In [83]:
print(new_ar_cd)

[[1 5 2]
 [3 6 4]]
